FROM fluent/fluentd:v1.16-debian
USER root

# Plugins necesarios para salida a RabbitMQ y parseo simple
RUN gem install --no-document fluent-plugin-rabbitmq fluent-plugin-parser

# Copia de configuración
COPY fluent.conf /fluentd/etc/fluent.conf

# Puerto de entrada (UDP 24224 según docker-compose)
EXPOSE 24224 24224/udp

USER fluent