FROM fluent/fluentd:v1.16-debian

USER root
# Instalar plugin de RabbitMQ para salida
RUN gem install fluent-plugin-rabbitmq --no-document

# Copiar configuración
COPY fluent.conf /fluentd/etc/fluent.conf

# Permisos y usuario no root
RUN chown -R fluent:fluent /fluentd
USER fluent

# Comando por defecto (del base image)